server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: officeRoutes
    consumer:
      group-id: OfficeGroupId
      auto-offset-reset: latest

application:
  stations:
    - name: "Station 1"
      x: 10
      y: 20
    - name: "Station 2"
      x: 70
      y: 40
    - name: "Station 3"
      x: 50
      y: 80

