server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: officeRoutes
    consumer:
      group-id: CarId
      auto-offset-reset: latest

application:
  cars:
    - name: "Car 1"
      location: "Station 1"
      speed: 3
    - name: "Car 1"
      location: "Station 1"
      speed: 4
    - name: "Car 1"
      location: "Station 2"
      speed: 3
